#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline as get_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile twitterHandle")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # Stores the twitter handle entered and ensure it is valid
    twitterUser = sys.argv[1]
    
    # Gets the twitter user's 50 most recent tweets and ensures
    # the tweets were returned. If no tweets were returned because they
    # haven't tweeted or don't exist, we exit the program.
    tuserTweets = get_timeline(twitterUser, 50)
    if tuserTweets == None:
        sys.exit("User not found")
    
    # For each tweet the user had made, analyze and see if it's
    # positive, negative, or neutral. Then print out the score
    # of the tweet alongside the tweet, colored green if
    # positive, red if negative, and yellow if neutral.
    for tweet in tuserTweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()
